IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME='FK_CardsTypes_ToCards') BEGIN;
	ALTER TABLE CardsTypes
	DROP CONSTRAINT FK_CardsTypes_ToCards;
END;
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME='FK_CardsTypes_ToTypes') BEGIN;
	ALTER TABLE CardsTypes
	DROP CONSTRAINT FK_CardsTypes_ToTypes;
END;
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = '') BEGIN;
	DROP TABLE CardsTypes;
END;
GO

CREATE TABLE [dbo].[CardsTypes]
(
	[CardsTypesId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[CardId] INT NOT NULL,
	[TypeId] INT NOT NULL, 
    CONSTRAINT [FK_CardsTypes_ToCards] FOREIGN KEY (CardId) REFERENCES [Cards]([CardId]),
	CONSTRAINT [FK_CardsTypes_ToTypes] FOREIGN KEY (TypeId) REFERENCES [Types]([TypeId]),
)