IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Rarities') BEGIN;
	DROP TABLE Rarities;
END;
GO

CREATE TABLE [dbo].[Rarities]
(
	[RarityId] INT NOT NULL PRIMARY KEY,
	[Name] varchar(50) NOT NULL
);
GO