IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Formats') BEGIN;
	DROP TABLE [Formats];
END;
GO

CREATE TABLE [dbo].[Formats]
(
	[FormatId] INT NOT NULL PRIMARY KEY,
	[Name] varchar(500) NOT NULL
);
GO