IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Artists') BEGIN;
	DROP TABLE Artists;
END;
GO

CREATE TABLE [dbo].[Artists]
(
	[ArtistId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] varchar(1000) NOT NULL
);
GO